### PR TITLE
fix: Fix the problem that the terminal exit fails

### LINKED ISSUE #7574: [Bug] The CPU is inexplicably consumed and cannot be downloaded.
### Contact Information

_No response_

### 1Panel Version

v1.10.20-lts

### Problem Description

最近查看监控面板发现1panel突然非常吃cpu，也没做什么特别操作
image
image
重启了1panel就降下来
image

### Steps to Reproduce

发现其中一个大概率重现步骤。点菜单“数据库”->"Redis"，会连接到已安装的redis，在终端输入redis命令，keys *查询，然后退出命令exit。然后1panel一直吃cpu

### The expected correct result

_No response_

### Related log output

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ssongliu**

### CODE REVIEW

File: backend/app/api/v1/terminal.go [hunk 1]
```diff
@@ -133,9 +132,9 @@ func (b *BaseApi) ContainerWsSSH(c *gin.Context) {
...
 	global.LOG.Info("websocket finished")
-	if wshandleError(wsConn, err) {
-		return
-	}
+	dt := time.Now().Add(time.Second)
+	_ = wsConn.WriteControl(websocket.CloseMessage, nil, dt)
+
 }
 
 func loadRedisInitCmd(c *gin.Context) (string, string, error) {
```
Comment (wanghe-fit2cloud) [inline backend/app/api/v1/terminal.go:140]: There seem to be no significant changes between the two versions of the provided Go code that could cause issues or performance bottlenecks. The primary difference appears to be in handling WebSocket connections within different methods, `WsSsh` and `ContainerWsSSH`, without substantial modification.

Here are a few observations:

1. Both functions use the same logic for closing the websocket connection using the `WriteControl` method with a `CloseMessage`.
2. They handle errors similarly by calling the same function (`wshandleError`) followed by returning if it returns true.
3. There is slight code repetition in both functions, which could theoretically be optimized slightly.

For further improvement:
- **Code DRYness**: Combine similar sections of code, especially around error handling, into helper functions where applicable.
- **Documentation Updates**: Ensure comments and documentation accuratelyreflect the current functionality, especially regarding when the `QuitChan` is handled.

In summary, the code remains mostly functional and should work correctly as implemented. However, there's scope for minor clean-up related to redundancy and improved readability.

File: frontend/src/components/terminal/index.vue [hunk 2]
```diff
@@ -202,10 +204,10 @@ const errorRealTerminal = (ex: any) => {
...
-        clearInterval(heartbeatTimer.value);
+        clearInterval(Number(heartbeatTimer.value));
     }
-    term.value.write('The connection has been disconnected.');
-    term.value.write(ev.reason);
+    term.value?.write('The connection has been disconnected.');
+    term.value?.write(ev.reason);
 };
 
 const isWsOpen = () => {
```
Comment (wanghe-fit2cloud) [inline frontend/src/components/terminal/index.vue:213]: There are no significant irregularities, potential issues, or optimization suggestions in the provided code changes. The most noticeable update from one line to another is using `Number()` when clearing the timer and ensuring that `term.value` exists before calling methods on it to avoid potential errors.

File: backend/utils/terminal/local_cmd.go [hunk 3]
```diff
@@ -100,4 +100,5 @@ func (lcmd *LocalCommand) Wait(quitChan chan bool) {
 		global.LOG.Errorf("ssh session wait failed, err: %v", err)
 		setQuit(quitChan)
 	}
+	setQuit(quitChan)
 }
```
Comment (wanghe-fit2cloud) [inline backend/utils/terminal/local_cmd.go:104]: The provided code snippet is mostly correct, but there are some minor improvements and clarifications that can be made:

### Improvements

1. **Redundant Line**: The line `setQuit(quitChan)` appears twice at different positions in the function. While it's not strictly necessary, you might want to decide whether one of these should be removed.

2. **Logical Clarity**: Consider adding a comment above this block explaining its purpose. This helps improve readability.

3. **Error Handling**: Ensure that `err` is defined before using it to prevent potential runtime errors.

Here's an updated version with these considerations:

```go
@@ -97,5 +96,8 @@ func (lcmd *LocalCommand) Wait(quitChan chan bool) {
         global.LOG.Errorf("ssh session wait failed, err: %v", err)
         setQuit(quitChan)
     }
+
+    // Function waits for SSH session to complete, handling any errors encountered.
+    // It also ensures that the quit channel is properly closed if an error occurs.
+    // Note: setQuit(quitChan) is called again here to ensure proper resource management.
+    setQuit(quitChan)
 }

```

### Optimization Suggestions:

- **Avoid Redundancy**: If only the first call to `setQuit(quitChan)` is needed, consider removing the second call. Only do what needs to be done once unless both calls have specific purposes.

- **Consistent Naming**: Consistently name variables and functions to improve maintainability and reduce bugs.

By making these adjustments, the code becomes more readable and potentially more efficient.

**Review by wanghe-fit2cloud — COMMENTED** [review]
/lgtm
